site_name: My Docs
theme:
    name: material
    palette:
        primary: black
        accent: red
    custom_dir: 'custom_dir'
extra_css:
    - custom_dir/custom.css


extra:
    search:
        language: 'jp'

extra_javascript:
    - custom_dir/custom.js