site_name: My Docs
theme:
    name: material
    palette:
        primary: black
        accent: red
    custom_dir: docs/custom_dir
extra:
    search:
        language: 'jp'
extra_css:
    - custom_dir/custom.css
extra_javascript:
    - custom_dir/custom.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
    - awesome-pages
